{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app038.fullname" . }}-config
  labels:
    {{- include "app038.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  APP_URL: "https://{{ .Values.ingress.hosts[0].host }}"
  REDIS_HOST: {{ include "app038.fullname" . }}-redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: {{ include "app038.fullname" . }}-rabbitmq
  RABBITMQ_PORT: "5672"
{{- end }}

