{{- if .Values.laravel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app038.fullname" . }}-laravel
  labels:
    {{- include "app038.laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.laravel.service.type }}
  ports:
    - port: {{ .Values.laravel.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app038.laravel.selectorLabels" . | nindent 4 }}
{{- end }}

