{{- if and .Values.laravel.enabled .Values.persistence.laravelStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage
  labels:
    {{- include "app038.laravel.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.laravelStorage.accessMode }}
  {{- if .Values.persistence.laravelStorage.storageClass }}
  storageClassName: {{ .Values.persistence.laravelStorage.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.laravelStorage.size }}
{{- end }}

