{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app038.fullname" . }}-rabbitmq
  labels:
    {{- include "app038.rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "app038.rabbitmq.selectorLabels" . | nindent 4 }}
{{- end }}

