{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app038.fullname" . }}-rabbitmq
  labels:
    {{- include "app038.rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      {{- include "app038.rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app038.rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        ports:
        - name: amqp
          containerPort: {{ .Values.rabbitmq.service.targetPort }}
          protocol: TCP
        - name: management
          containerPort: {{ .Values.rabbitmq.service.managementTargetPort }}
          protocol: TCP
        env:
        {{- if .Values.rabbitmq.credentials.secretName }}
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.credentials.secretName }}
              key: {{ .Values.rabbitmq.credentials.usernameKey }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.credentials.secretName }}
              key: {{ .Values.rabbitmq.credentials.passwordKey }}
        {{- end }}
        {{- if .Values.rabbitmq.persistence.enabled }}
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.rabbitmq.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.rabbitmq.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.rabbitmq.resources | nindent 10 }}
      {{- if .Values.rabbitmq.persistence.enabled }}
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: {{ include "app038.fullname" . }}-rabbitmq
      {{- end }}
      {{- with .Values.rabbitmq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

