{{- if .Values.svelte.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app038.fullname" . }}-svelte
  labels:
    {{- include "app038.svelte.labels" . | nindent 4 }}
spec:
  {{- if not .Values.svelte.autoscaling.enabled }}
  replicas: {{ .Values.svelte.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app038.svelte.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app038.svelte.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.svelte.podSecurityContext | nindent 8 }}
      containers:
      - name: svelte
        securityContext:
          {{- toYaml .Values.svelte.securityContext | nindent 12 }}
        image: "{{ include "app038.svelte.imageRepository" . }}:{{ .Values.svelte.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.svelte.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.svelte.service.targetPort }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.svelte.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.svelte.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.svelte.resources | nindent 10 }}
      {{- with .Values.svelte.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.svelte.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.svelte.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

